show_author_username:
  type: bool
  default: false
  description:
    en: "Show author usernames instead profile avatars in all topic list pages."
poster_column_label:
  type: string
  default: "Author"
  description:
    en: "Text lable for the author or last poster column header."
